/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plotter;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fsan
 */
public class Plotter2 extends javax.swing.JFrame {

    /**
     * Creates new form Plotter2
     */
    
    protected boolean isNormal;
    protected Plotter parent;
    private boolean exists;
    protected String filepath;
    
    public Plotter2(boolean isNormal, Plotter parent, String filePath) {
        this.parent = parent;
        this.isNormal = isNormal;
        this.exists = true;
        this.filepath = filePath;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_loadAnother = new javax.swing.JButton();
        b_silhouette = new javax.swing.JButton();
        b_reachability = new javax.swing.JButton();
        l_file = new javax.swing.JLabel();
        l_help = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(l_file.getText()+" - Plotter");
        setMaximumSize(new java.awt.Dimension(340, 175));
        setMinimumSize(new java.awt.Dimension(340, 175));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        b_loadAnother.setText("Load Another File");
        b_loadAnother.setEnabled(false);
        b_loadAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loadAnotherActionPerformed(evt);
            }
        });

        b_silhouette.setText("Silhouette Plot");
        b_silhouette.setEnabled(false);
        b_silhouette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_silhouetteActionPerformed(evt);
            }
        });

        b_reachability.setText("Reachability Plot");
        b_reachability.setEnabled(false);
        b_reachability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reachabilityActionPerformed(evt);
            }
        });

        l_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plotter/Info.png"))); // NOI18N
        l_help.setText("Help");
        l_help.setToolTipText("More Information");
        l_help.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        l_help.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 1, 1));
        l_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_helpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_silhouette)
                        .addGap(18, 18, 18)
                        .addComponent(b_reachability))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(b_loadAnother)))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(l_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_help))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_file, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_help))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_silhouette)
                    .addComponent(b_reachability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(b_loadAnother)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setFileLabel(String label)
    {
        this.l_file.setText(label);
        
    }
    
    private void b_loadAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loadAnotherActionPerformed
       this.setVisible(false);
       this.parent.setVisible(true);
       
    }//GEN-LAST:event_b_loadAnotherActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void l_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_helpMouseClicked
        JOptionPane.showMessageDialog(this, "In the case of a shaved load the Reachability-plot, will be disabled.\n"+
                                            "The silhouette-plot shows the hierarchy of clusters in many diferent density levels (density as 1/eps).\n"+
                                            "The reachability-plot shows the reachability distance of all the objects.\n"
                                        +   "For more information refer to:\n"+
                                            "--GUPTA G.; LIU, A.; GHOSH, J.; Automated Hierarchical Density Shaving: A Robust Automated Clustering and Visualization Framework for Large Biological Data Sets.\n"+
                                            "IEEE/ACM Transactions on Computational Biology and Bioinformatics. 2010.\n"+
                                            "DOI: http://dx.doi.org/10.1109/TCBB.2008.32\n"+
                                            "--ANKERST, M.; BREUNIG, M. M.; KRIEGEL, H. P.; SANDER, J.; OPTICS: Ordering Points To Identify the Clustering Structure.\n"+
                                            "ACM International Conference on Management of Data (SIGMOD), Philadelphia. p. 49–60. 1999.\n"+
                                            "DOI: http://dx.doi.org/10.1145/304182.304187");
    }//GEN-LAST:event_l_helpMouseClicked

    private void b_silhouetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_silhouetteActionPerformed
        String filename = this.filepath;
        String title = "Silhouette-like Plot | ";
        if(!isNormal)
        {
            title += "rshave="+String.format(String.valueOf(parent.rShave*100),"%.2f")+"% | ";
        }
        title += filename;
        SilhouettePlotFrame sp = new SilhouettePlotFrame(parent.getMatrix(), parent.getDensities(), parent.getMaxCluster(), parent.getColors());
        sp.setTitle(title);
        sp.setExtendedState(MAXIMIZED_BOTH);
        sp.setVisible(true);
    }//GEN-LAST:event_b_silhouetteActionPerformed

    private void b_reachabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reachabilityActionPerformed

        String filename = this.l_file.getText();
        String title = "Reachability Plot: "+filename;
        ReachabilityPlotFrame rp = new ReachabilityPlotFrame(parent.getMatrix(), parent.getDensities());
        rp.setTitle(title);
        rp.setExtendedState(MAXIMIZED_BOTH);
        rp.setVisible(true);
    }//GEN-LAST:event_b_reachabilityActionPerformed
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_loadAnother;
    private javax.swing.JButton b_reachability;
    private javax.swing.JButton b_silhouette;
    private javax.swing.JLabel l_file;
    private javax.swing.JLabel l_help;
    // End of variables declaration//GEN-END:variables

    
    void enableAllButtons() {
        this.b_loadAnother.setEnabled(true);
        this.b_silhouette.setEnabled(true);
        if(this.isNormal)
        {
            this.b_reachability.setEnabled(true);
        }
        else
        {
            this.b_reachability.setEnabled(false);
        }
    }
    
}
